### ISSUE TITLE
4channer spiking CPU in the background

### ISSUE THREAD

**Issue by johnarleyburns** [grzegorznittner/chanu#101]
even when not running 4channer my phone can become unresponsive and halt for 5-10 sec, I look at the task manager and see 4channer running at 30% CPU, also must be doing something on UI thread.  Even after this 4channer stays pegged at between 4-8% CPU all the time.

We should reduce the amount of time we spend scheduling background stuff, only do what is most important and do it quickly.

**Comment by johnarleyburns** [comment]
Investigation: waited until next spike and unresponsive 4chan (while in other app), get a bunch of exceptions like this:

01-30 20:48:10.009: INFO/(19369): Loaded thread q/396771 posts 25
01-30 20:48:10.009: WARN/MessageQueue(19369): Handler (com.chanapps.four.handler.LoaderHandler) {41b6d638} sending message to a Handler on a dead thread
        java.lang.RuntimeException: Handler (com.chanapps.four.handler.LoaderHandler) {41b6d638} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:294)
        at android.os.Handler.sendMessageAtTime(Handler.java:473)
        at android.os.Handler.sendMessageDelayed(Handler.java:446)
        at android.os.Handler.sendEmptyMessageDelayed(Handler.java:410)
        at android.os.Handler.sendEmptyMessage(Handler.java:395)
        at com.chanapps.four.service.profile.MobileProfile.onDataParseSuccess(MobileProfile.java:284)
        at com.chanapps.four.service.NetworkProfileManager.finishedParsingData(NetworkProfileManager.java:196)
        at com.chanapps.four.service.ThreadParserService.onHandleIntent(ThreadParserService.java:129)
        at com.chanapps.four.service.BaseChanService$ServiceHandler.handleMessage(BaseChanService.java:91)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.os.HandlerThread.run(HandlerThread.java:60)

then noticed this:

1-30 20:48:16.409: INFO/UpdateWidgetService(19369): Null bitmap for url=http://0.thumbs.4chan.org/w/thumb/1358307715351s.jpg
01-30 20:48:16.439: INFO/UpdateWidgetService(19369): Null bitmap for url=http://0.thumbs.4chan.org/w/thumb/1359533558060s.jpg
01-30 20:48:16.504: INFO/UpdateWidgetService(19369): Null bitmap for url=http://0.thumbs.4chan.org/w/thumb/1359529125276s.jpg
01-30 20:48:16.544: INFO/UpdateWidgetService(19369): Null bitmap for url=http://0.thumbs.4chan.org/e/thumb/1359564808943s.jpg
01-30 20:48:16.579: INFO/UpdateWidgetService(19369): Null bitmap for url=http://0.thumbs.4chan.org/e/thumb/1358829720649s.jpg
01-30 20:48:16.609: INFO/UpdateWidgetService(19369): Null bitmap for url=http://0.thumbs.4chan.org/e/thumb/1356144969494s.jpg
01-30 20:48:16.684: INFO/UpdateWidgetService(19369): Null bitmap for url=http://0.thumbs.4chan.org/p/thumb/1359548714667s.jpg
01-30 20:48:16.759: INFO/UpdateWidgetService(19369): Null bitmap for url=http://0.thumbs.4chan.org/p/thumb/1359572407770s.jpg
01-30 20:48:16.794: INFO/UpdateWidgetService(19369): Null bitmap for url=http://0.thumbs.4chan.org/p/thumb/1359554159548s.jpg

then this:

01-30 20:48:42.534: INFO/ChanGridSizer(19369): sizeGridToDisplay width: 720, height: 1280, numCols: 2
01-30 20:48:42.539: INFO/ChanGridSizer(19369): sizeGridToDisplay width: 720, height: 1280, numCols: 2
01-30 20:48:43.279: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/e
01-30 20:48:43.489: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/q
01-30 20:48:43.709: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/tv
01-30 20:48:43.714: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/a
01-30 20:48:44.054: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/w
01-30 20:48:44.164: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/p
01-30 20:48:44.344: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/3
01-30 20:48:44.344: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/adv
01-30 20:48:44.349: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/an
01-30 20:48:44.349: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/b
01-30 20:48:44.634: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/c
01-30 20:48:44.634: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/cgl
01-30 20:48:44.664: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/ck
01-30 20:48:44.699: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/cm
01-30 20:48:44.704: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/co
01-30 20:48:44.709: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/d
01-30 20:48:44.709: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/diy
01-30 20:48:44.714: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/fa
01-30 20:48:44.714: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/fit
01-30 20:48:44.794: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/g
01-30 20:48:44.819: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/gif
01-30 20:48:44.819: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/h
01-30 20:48:44.824: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/hc
01-30 20:48:44.824: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/hm
01-30 20:48:44.824: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/hr
01-30 20:48:44.824: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/i
01-30 20:48:44.829: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/ic
01-30 20:48:44.829: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/int
01-30 20:48:44.879: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/jp
01-30 20:48:44.884: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/k
01-30 20:48:44.894: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/lit
01-30 20:48:44.894: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/m
01-30 20:48:44.919: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/mlp
01-30 20:48:44.919: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/mu
01-30 20:48:44.919: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/n
01-30 20:48:44.924: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/o
01-30 20:48:44.974: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/po
01-30 20:48:44.979: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/pol
01-30 20:48:44.994: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/r
01-30 20:48:44.994: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/r9k
01-30 20:48:45.004: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/s
01-30 20:48:45.064: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/sci
01-30 20:48:45.064: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/soc
01-30 20:48:45.064: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/sp
01-30 20:48:45.109: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/t
01-30 20:48:45.109: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/tg
01-30 20:48:45.114: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/toy
01-30 20:48:45.114: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/trv
01-30 20:48:45.114: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/u
01-30 20:48:45.129: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/v
01-30 20:48:45.209: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/vg
01-30 20:48:45.214: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/vp
01-30 20:48:45.214: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/wg
01-30 20:48:45.214: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/wsg
01-30 20:48:45.219: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/x
01-30 20:48:45.219: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/y
01-30 20:48:45.849: INFO/CleanUpService(19369): Checking folder /storage/sdcard0/Android/data/com.chanapps.four.activity/cache/wallpapers

then a bunch of these:

01-30 20:48:58.049: INFO/UpdateWidgetService(19369): Null bitmap for url=http://0.thumbs.4chan.org/w/thumb/1358307715351s.jpg
01-30 20:48:58.149: INFO/UpdateWidgetService(19369): Null bitmap for url=http://0.thumbs.4chan.org/w/thumb/1359533558060s.jpg
01-30 20:48:58.194: INFO/UpdateWidgetService(19369): Null bitmap for url=http://0.thumbs.4chan.org/w/thumb/1359529125276s.jpg
01-30 20:48:58.244: INFO/UpdateWidgetService(19369): Null bitmap for url=http://0.thumbs.4chan.org/q/thumb/1359554648334s.jpg
01-30 20:48:58.364: INFO/UpdateWidgetService(19369): Null bitmap for url=http://0.thumbs.4chan.org/q/thumb/1359458416912s.jpg
01-30 20:48:58.399: INFO/UpdateWidgetService(19369): Null bitmap for url=http://0.thumbs.4chan.org/q/thumb/1359562899204s.jpg
01-30 20:48:58.804: INFO/UpdateWidgetService(19369): Null bitmap for url=http://0.thumbs.4chan.org/a/thumb/1359512171134s.jpg
01-30 20:48:58.839: INFO/UpdateWidgetService(19369): Null bitmap for url=http://0.thumbs.4chan.org/a/thumb/1359505951219s.jpg
01-30 20:48:58.919: ERROR/UpdateWidgetService(19369): Exception downloading image for board=a i=2 imageUrl=
        java.io.FileNotFoundException: http://0.thumbs.4chan.org/a/thumb/1359513534702s.jpg
        at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:177)
        at com.chanapps.four.widget.UpdateWidgetService$WidgetUpdateTask.loadBitmaps(UpdateWidgetService.java:168)
        at com.chanapps.four.widget.UpdateWidgetService$WidgetUpdateTask.doInBackground(UpdateWidgetService.java:97)
        at com.chanapps.four.widget.UpdateWidgetService$WidgetUpdateTask.doInBackground(UpdateWidgetService.java:63)
        at android.os.AsyncTask$2.call(AsyncTask.java:287)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:137)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
        at java.lang.Thread.run(Thread.java:856)
