### ISSUE TITLE
Full Screen Galley View is crashing frequently

### ISSUE THREAD

**Issue by johnarleyburns** [grzegorznittner/chanu#134]
Go into full screen view, click to go forward or backwards to view a few images, app will crash.  Can never view more than 3-5 images without crashing.  Probably related to not freeing/recycling bitmap efficiently when using forwards/back buttons.  Might not be a problem if gallery can point directly to a folder, removing the forward/back buttons.  Exception

02-08 11:58:29.390: ERROR/AndroidRuntime(13002): FATAL EXCEPTION: GLThread 1929
        java.lang.OutOfMemoryError
        at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:623)
        at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:476)
        at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:499)
        at com.android.gallery3d.ui.ResourceTexture.onGetBitmap(ResourceTexture.java:42)
        at com.android.gallery3d.ui.UploadedTexture.getBitmap(UploadedTexture.java:125)
        at com.android.gallery3d.ui.UploadedTexture.getHeight(UploadedTexture.java:153)
        at com.android.gallery3d.ui.ResourceTexture.getHeight(ResourceTexture.java:27)
        at com.android.gallery3d.ui.EdgeEffect$Drawable.getIntrinsicHeight(EdgeEffect.java:421)

**Comment by grzegorznittner** [comment]
I disabled Gallery view till I get this issue sorted out.

**Comment by mirceapopro** [comment]
calling the recycle method on the Bitmap when the activity is paused.

**Comment by johnarleyburns** [comment]
Still seems to crash pretty consistently on loading 5th image in gallery view, at least on SIII.

**Comment by johnarleyburns** [comment]
Even with 200+ images, working fine now without crashing.
