### ISSUE TITLE
User sees white page when 4chan returns error for catalog

### ISSUE THREAD

**Issue by grzegorznittner** [grzegorznittner/chanu#311]
Catalog.json was not found which caused empty page (white).
We need to display message instead.

Got this exception:
IO Error fetching Chan board json
    java.io.FileNotFoundException: http://api.4chan.org/wg/catalog.json
    at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:177)
    at java.net.URLConnection.getContent(URLConnection.java:195)
    at com.chanapps.four.service.FetchChanDataService.handleBoard(FetchChanDataService.java:254)
    at com.chanapps.four.service.FetchChanDataService.onHandleIntent(FetchChanDataService.java:173)
    at com.chanapps.four.service.BaseChanService$ServiceHandler.handleMessage(BaseChanService.java:93)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:155)
    at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by grzegorznittner** [comment]
Similar thing happened when thread data were not returned.
User is not informed that data were not fetched from 4chan.
