### ISSUE TITLE
Got a whole bunch of these exceptions loading a board and then boom crashed

### ISSUE THREAD

**Issue by johnarleyburns** [grzegorznittner/chanu#73]
01-20 20:49:39.730: ERROR/FetchChanDataService(17285): IO Error reading Chan thread json. Wrong content type returned 'text/html'
        java.io.IOException: Wrong content type returned 'text/html'
        at com.chanapps.four.service.FetchChanDataService.handleThread(FetchChanDataService.java:296)
        at com.chanapps.four.service.FetchChanDataService.onHandleIntent(FetchChanDataService.java:175)
        at com.chanapps.four.service.BaseChanService$ServiceHandler.handleMessage(BaseChanService.java:119)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by johnarleyburns** [comment]
Those exceptions are probably unrelated to the crash:

01-20 22:42:07.630: ERROR/AndroidRuntime(3971): FATAL EXCEPTION: main
        java.lang.RuntimeException: Unable to instantiate application android.app.Application: java.lang.NullPointerException
        at android.app.LoadedApk.makeApplication(LoadedApk.java:501)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4201)
        at android.app.ActivityThread.access$1300(ActivityThread.java:140)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1287)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4898)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
        at dalvik.system.NativeStart.main(Native Method)
        Caused by: java.lang.NullPointerException
        at android.app.LoadedApk.initializeJavaContextClassLoader(LoadedApk.java:377)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:320)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:493)
        ... 11 more

**Comment by johnarleyburns** [comment]
fixed by handling boards better when error is received
